### ISSUE TITLE
DELETE method not working

### ISSUE THREAD

**Issue by reflog** [srhyne/jQuery-Parse#1]
Hi there.
I'm testing this nice Parse wrapper you've made and it works really nice, except for the DELETE method.
When I call: 
 $.parse.delete("Package/"+oID, function(){
                    reload();
                });
The callback is never called and after some debugging, I see that I land in this method:

function _error(jqXHR, textStatus, errorThrown){ }

With all the parameters empty.

The POST and GET methods are working very nice, so I can't seem to figure out what the problem is...
Any ideas?

**Comment by srhyne** [comment]
Hi Eli, 

Hmmm, what browser and browser version are you using for development? I think some browsers do not support PUT & DELETE. I can't quite nail down which browsers have problems. Or is it the doctype that effects it? 

[stackoverflow post](http://stackoverflow.com/questions/165779/are-the-put-delete-head-etc-methods-available-in-most-web-browsers)

 The _error method is just a default error catch for the $.ajax method. If the delete method doesn't work in the parse.html demo than we know that it's a browser issue. 

Let me know ;)

**Comment by reflog** [comment]
My apologies, seems this was just my JavaScript noobness. It's all working very well.
Thanks for the great component!
