### ISSUE TITLE
Security Vulnerability

### ISSUE THREAD

**Issue by jzeltman** [srhyne/jQuery-Parse#13]
I really am enjoying using your plugin here, and am in the process of making an app with it and Backbone.js, so I'm also interested in the Backbone extension here. The issue that I'm raising is the fact that the app key and the rest key are both super visible with this, which presents obvious security concerns. Any thoughts on circumventing this issue? Potentially a server side solution to pass a token with those keys to kick the app off?

**Comment by srhyne** [comment]
Hi Joshua, 

[Just merged in support for Parse's session token header..](https://github.com/srhyne/jQuery-Parse/commit/3c379347fd3a8c9cc639ffe591a5925a36ec9ff6)

Thank [brendannee](https://github.com/brendannee) for that one.

[Here are the parse docs for the session token system.](https://www.parse.com/docs/rest#users-security)
