### ISSUE TITLE
requestPasswordReset spelled incorrectly in the README example.

### ISSUE THREAD

**Issue by aaronfrey** [srhyne/jQuery-Parse#18]
The example reads
`$.parse.requstPasswordReset('testy@test.com', optionalCallback, optionalErrorCallback);`
where it should read `$.parse.requestPasswordReset('testy@test.com', optionalCallback, optionalErrorCallback);`
I realize I may be the only idiot who copies directly from documentation, but maybe that will save someone else some time.

**Comment by srhyne** [comment]
@aaronfrey fixed ;-) Let me know if you find any more. Be well!
