### ISSUE TITLE
$.parse:error Not Found

### ISSUE THREAD

**Issue by ghost** [srhyne/jQuery-Parse#2]
I am trying to use this on my wordpress website. I am getting exception called ($.parse:error Not Found) when I try to load the page. It is saying that exception is Uncaught in 'jquery.js'.

I am very new in Web development, so please bear with me.

Thanks,
Amit

**Comment by ghost** [comment]
Sorry, it was my mistake. I was calling 'put' instead of 'post'.

**Comment by srhyne** [comment]
Thanks for closing the ticket Amit! Happy parsing.
