### ISSUE TITLE
Add to array

### ISSUE THREAD

**Issue by grebbekevin** [srhyne/jQuery-Parse#20]
Is there a way to add a value to a array with the jquery parse class?

**Comment by srhyne** [comment]
Hi Kevin, 

Is it Kevin?  Yes, I'm pretty confident you can do this without any changes at the moment. 

From the docs, you can see that adding to an array is simply just nested JSON. 

![Image ](http://note.io/1BbYlrw)

So in $.parse.. 

```
var update = { 
    skills : {
        __op : 'AddUnique',
        objects : ['flying', 'kungfu']
    }
};

$.parse.put("Class/" + id, update, function(json) { console.log('updated ' + id, json) });
```

So it's just like a regular update but with a specific JSON format
