### ISSUE TITLE
Is it possible to perform queries that specify ranges of dates?

### ISSUE THREAD

**Issue by rogersnick** [srhyne/jQuery-Parse#21]
ie - where:
{ createdAt:
    {"$lt":somedate,
     "$gte":somelaterdate 
   }
}

**Comment by sorrento** [comment]
Hi, I did a similar restriction in a query and it worked.

`$.parse.get("Player",{where:{active:{$ne:false}}}, function(json) {...`

As you see it is not needed to put quotes

Hope it helps!
