### ISSUE TITLE
any news on backbone extension

### ISSUE THREAD

**Issue by lukeholder** [srhyne/jQuery-Parse#4]
how can I use this in backbone app?

**Comment by srhyne** [comment]
Hi Luke,

You need to overwrite backbone.sync or a add a sync method to your model. The use $.parse as a replacement. Check this out. http://documentcloud.github.com/backbone/docs/backbone-localstorage.html . I will definitely make an example as soon as I get home from my roadtrip. ;)

**Comment by alfrednerstu** [comment]
Great project, the demo were amazing! Would love to see Ember.js and/or Page.js sync as well.

**Comment by srhyne** [comment]
Hi Alfred, 

Glad you liked the demo. I'll add Ember and Page to the TODO's on the readme. I definitely need to get some more library support.

**Comment by jzeltman** [comment]
Just wanted to bump this one as well, because I'm really interested in it ;)

**Comment by srhyne** [comment]
Luke & Joshua, 

Working on it ;) It will be an add on $.parse method that is in it's on file. You will be able to override Backbone.sync or a individual models, collections with `$.parse.backbone` or should I attach to backbone? Backbone.parse.. Hmmm.

**Comment by jzeltman** [comment]
Stephen, 

I've also been looking at this set of backbone and parse related work by Brian Genisio. Don't know if that offers any help, but thought I'd share.

http://houseofbilz.com/archives/2011/11/07/going-mostly-server-less-with-backbone-js/

**Comment by srhyne** [comment]
Yeah, been reading this ;)

**Comment by srhyne** [comment]
[check it!](https://github.com/srhyne/jQuery-Parse/commit/c3b757c7cca5087d215623f7eb1442e338cc0ad0)

Will add a full-fledged demo soon. Thanks everyone for the "nudging" ;)
