### ISSUE TITLE
How to run demo?

### ISSUE THREAD

**Issue by kszeto** [srhyne/jQuery-Parse#7]
This is a dumb question because I am new to web development.  How do I get the demo to run? It does not seem to do anything.  THanks.

**Comment by srhyne** [comment]
Hi, 
- In your Parse.com account, create a app named "demo"
- Pass your "demo" application key & rest key to `$.parse.init` in demo.js (line 7-8)

```
  $.parse.init({
       app_id: undefined, // <-- enter your Application Id here
       rest_key: undefined // <--enter your REST API Key here   
  });
```
- Then try out the demo.

**Comment by srhyne** [comment]
Closing this issue. Let me know if you need any more help.

**Comment by kszeto** [comment]
I responded to your answer yesterday by email but it appears that it did not get through.  Here it my response again:

"My apologies that I should be more specific in my original question.  I have already created "demo" in Parse.com and inserted the app key and reset key in demo.js.  My problem is to figure out what the exact command to use as input.  Nothing I tried worked and whatever I put in always comes back with the red Remove button."

Thanks.

**Comment by kszeto** [comment]
Hi Stephen,

I responded to your answer yesterday by email but it appears that it did not get through. Here is my response again:

"My apologies that I should be more specific in my original question. I have already created "demo" in Parse.com and inserted the app key and reset key in demo.js. My problem is to figure out what the exact command to use as input. Nothing I tried worked and whatever I put in always comes back with the red Remove button."

Thanks.

Best Regards,

Koon Szeto

-----Original Message-----

**Comment by srhyne** [comment]
Koon, 

The red remove button's are part of the demo ;) The goal of the demo is to show you how $.parse[get, post, put, delete] are used. [Please try the new demo here](http://srhyne.github.com/jQuery-Parse/)

This one doesn't even require you to change files and it shows you successful $.parse methods executed in a logger on the right. Check it out and let me know what you think ;)

**Comment by kszeto** [comment]
Stephen,

This version works great for me.  I am able to create, delete and edit object in the "tasks" class.  

Thanks.

**Comment by srhyne** [comment]
That's great! I'm glad it's working now for you.
