### ISSUE TITLE
Relational Queries

### ISSUE THREAD

**Issue by danlipert** [srhyne/jQuery-Parse#9]
Is there a way to do a relational query with this library?  I'd love to have this functionality :)

I tried doing

```
$.parse.get("Item", {
                    where : {'user' : user}},
```

and 

```
$.parse.get("Item", {
                    where : {'user' : "{\"__type\" : \"Pointer\", \"className\" : \"_User\", \"objectId\" : \"" + user.objectId + "\"}"};},
```

The first one returned bad request because it serializes the json instead of setting up Parse's pointer info, the second one oddly returns 200 so maybe it is supported after all and I'm missing a detail in the forming of the request.

**Comment by srhyne** [comment]
Hi, 

Yeah, I definitely don't think that is possible to pass an object as a key. You need to user a single foreign key I think, but if you found a way to do it let me know!
